### ISSUE TITLE
Hotkey doesn't work on Nordic keyboard layout

### ISSUE THREAD

**Issue by Opinion** [ChaseStrackbein/m3-dev-console#1]
Nordic keyboard layouts have ``[ ` ]`` left of the backspace key and can't be listened to for hotkeys because shift must be held to make that character. It's an annoyance to use backticks in general for us because `[ SHIFT ]`+``[ ` ]`` must be pressed twice and then we always get two of them.

For Nordic keyboards, `[ | ]` (pipe) is left of the `[ 1 ]` key and is the equivalent to US's ``[ ` ]``

![image](https://user-images.githubusercontent.com/58629082/142766233-1082dcc6-4b43-4802-83d3-41307c9c2975.png)

Please make this configurable!

\<Opinion>

**Comment by ChaseStrackbein** [comment]
Thanks for the feedback! dev.Console actually hooks into another one of my mods available on M3, [Keybindings](https://github.com/ChaseStrackbein/melvor-keybindings) to allow for this configuration.

However, I'll take this issue to do something I've meant to add, which is a button at the top of the page to toggle the console as well.

**Comment by Opinion** [comment]
Sweet! I wasn't aware it hooked into Keybindings mod. 

Maybe you could add a note about this feature in the readme, and maybe mention it needs to be loaded after the keybindings mod in the load order?

**Comment by ChaseStrackbein** [comment]
- Added buttons to toggle the console without the hotkey (find in the game's main header once loaded into a character)
- Added notes on the hotkey being configurable via Keybindings in the README

Resolved with 64d18546ef8a54f09db8da5ed52899dbe549c223 and b75fdf0d410cbcc5ab3b60314e3a2d8bfb91ecdf
